// <auto-generated />
using ASP.NET_TASK1.Models.DirModels;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ASP.NET_TASK1.Migrations
{
    [DbContext(typeof(DirsContext))]
    [Migration("20230707133855_init")]
    partial class init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ASP.NET_TASK1.Models.DirModels.Dir", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(55)
                        .HasColumnType("nvarchar(55)");

                    b.HasKey("Id");

                    b.ToTable("Dirs");
                });

            modelBuilder.Entity("ASP.NET_TASK1.Models.DirModels.DirRelation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Id_Child")
                        .HasColumnType("int");

                    b.Property<int>("Id_Parent")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Id_Child");

                    b.HasIndex("Id_Parent");

                    b.ToTable("DirRelations");
                });

            modelBuilder.Entity("ASP.NET_TASK1.Models.DirModels.DirRelation", b =>
                {
                    b.HasOne("ASP.NET_TASK1.Models.DirModels.Dir", "Child")
                        .WithMany()
                        .HasForeignKey("Id_Child")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ASP.NET_TASK1.Models.DirModels.Dir", "Parent")
                        .WithMany()
                        .HasForeignKey("Id_Parent")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Child");

                    b.Navigation("Parent");
                });
#pragma warning restore 612, 618
        }
    }
}
