// <auto-generated />
using ASP.NET_TASK1.Models.DirModels;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ASP.NET_TASK1.Migrations
{
    [DbContext(typeof(DirsContext))]
    partial class DirsContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ASP.NET_TASK1.Models.DirModels.Dir", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(55)
                        .HasColumnType("nvarchar(55)");

                    b.HasKey("Id");

                    b.ToTable("Dirs", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Creating Digital Images"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Resources"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Primary Sources"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Secondary Sources"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Evidence"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Graphic Products"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Process"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Final Product"
                        });
                });

            modelBuilder.Entity("ASP.NET_TASK1.Models.DirModels.DirRelation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Id_Child")
                        .HasColumnType("int");

                    b.Property<int>("Id_Parent")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Id_Child");

                    b.HasIndex("Id_Parent");

                    b.ToTable("DirRelations", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Id_Child = 2,
                            Id_Parent = 1
                        },
                        new
                        {
                            Id = 2,
                            Id_Child = 5,
                            Id_Parent = 1
                        },
                        new
                        {
                            Id = 3,
                            Id_Child = 6,
                            Id_Parent = 1
                        },
                        new
                        {
                            Id = 4,
                            Id_Child = 3,
                            Id_Parent = 2
                        },
                        new
                        {
                            Id = 5,
                            Id_Child = 4,
                            Id_Parent = 2
                        },
                        new
                        {
                            Id = 6,
                            Id_Child = 7,
                            Id_Parent = 6
                        },
                        new
                        {
                            Id = 7,
                            Id_Child = 8,
                            Id_Parent = 6
                        });
                });

            modelBuilder.Entity("ASP.NET_TASK1.Models.DirModels.DirRelation", b =>
                {
                    b.HasOne("ASP.NET_TASK1.Models.DirModels.Dir", "Child")
                        .WithMany()
                        .HasForeignKey("Id_Child")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ASP.NET_TASK1.Models.DirModels.Dir", "Parent")
                        .WithMany()
                        .HasForeignKey("Id_Parent")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Child");

                    b.Navigation("Parent");
                });
#pragma warning restore 612, 618
        }
    }
}
